### ISSUE TITLE
training error only for YCB data

### ISSUE THREAD

**Issue by MinWang1997** [ethnhe/FFB6D#34]
Hi all,

I run the default setting of train_ycb.py several times and got different errors each time.
[](url)
The first time:
`FileNotFoundError: [Errno 2] No [such] file or directory: '/home/mwa7rng/FFB6D/ffb6d/datasets/ycb/YCB_Video_Dataset/data_syn/050106-depth.png'`
However, I do have this <img width="127" alt="2021-08-30_19h53_58" src="https://user-images.githubusercontent.com/75472853/131846736-1bc1f97a-4dd5-45e1-8571-49b6fb6179b4.png">

The second time:
```
RuntimeError: No CUDA GPUs are available
RuntimeError: No CUDA GPUs are available
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 28276) of binary: /home/mwa7rng/.conda/envs/ffb6dtest/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
```

Then I check my cuda by
![cuda](https://user-images.githubusercontent.com/75472853/131847946-3808b420-2b3e-42bb-a3db-22e7f0810e7b.png)

The third: 
```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 35290) of binary: /home/mwa7rng/.conda/envs/ffb6dtest/bin/python3
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
```

The fourth:

```
RuntimeError: 
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
CUDA error: invalid device ordinal
```

Training Linemod dataset works but training ycb data failed.
Does anyone know why?

I attached all the errors here.
[errors.zip](https://github.com/ethnhe/FFB6D/files/7099026/errors.zip)

**Comment by minwang-ai** [comment]
I solved the issue by using the same number of GPUs with same memory and also correct the train_ycb.py by refering train_lm.py

**Comment by HannahHaensen** [comment]
@MinWang1997 could you provide your solution for ycb? thanks in advance :)
