### ISSUE TITLE
 CUDA out of memory related to data parallel

### ISSUE THREAD

**Issue by taeyeop-lee** [ethnhe/FFB6D#35]
I have a simple question related to data parallel. 
When I run train_lm.sh https://github.com/ethnhe/FFB6D/blob/master/ffb6d/train_lm.sh
When I ran the script, I got out of memory.
My main problem comes from the 0 GPU get more memories than others.
Q1. Have you experienced similar issues?? or this phenomenon is natural??

Current my GPU is TITAN Xp.
![Screenshot from 2021-09-05 12-50-37](https://user-images.githubusercontent.com/50736858/132114439-68c06066-5705-4908-832e-ef7911639e29.png)

**Comment by taeyeop-lee** [comment]
I solved the problem using some tricks. 
If you can share some comments related to your experiences, It would be really helpful. 

https://github.com/ethnhe/FFB6D/blob/3579a69df27451f74f3abc06964bba1bc7d40605/ffb6d/train_lm.py#L109

I changed CUDA_VISIBLE_DEVICES and others
```
os.environ['CUDA_VISIBLE_DEVICES'] = str(args.local_rank)
torch.cuda.set_device(0)
device = torch.device('cuda:{}'.format(0))
model = torch.nn.parallel.DistributedDataParallel(
model, device_ids=[0], output_device=0,
find_unused_parameters=True)
```

**Comment by an99990** [comment]
hey @taeyeop-lee  i just tried changing the lines like you did. I get the error that model is not defined for this
```
model = torch.nn.parallel.DistributedDataParallel(
model, device_ids=[0], output_device=0,
find_unused_parameters=True)
```
